name = "Kant"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a2b426684b3d871595afbf234fde884db2a63b2af31b82516a1c016e4c43d2b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
