name = "Kant"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e41216b24204dbd2cba2d5fc047538b07067fe3ff74bbbed47d014c6d4e75d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
